PR of Phase2
Star-Academy/Summer1400-SE-Team14 pull request #3
Opened 2021-07-26 08:36 UTC by mjmaher987

2021-07-26 09:42 UTC, MKasaei00 requested changes
بیش‌تر به تک وظیفه بودن توابع و کلاس‌ها توجه کنین :)

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/InvertedIndex.java
> +            for (String _word : line.split("\\W+")) {
جدا کردن و تبدیل فایل به توکن‌های مختلف وظیفه‌ی یک تابع مجزاست.

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/InvertedIndex.java
> +            String word = words.toLowerCase();
نرمال‌سازی کلمات ورودی وظیفه ی یک تابع جداست

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/InvertedIndex.java
> +    }
برای منها کردن دو ست از هم تابع آماده هست

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/InvertedIndex.java
> +    }
نیازی نیست خودتون بنویسید

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/Main.java
> +        File directoryPath = new File("C:\\Users\\mjmah\\IdeaProjects\\codestar-intern-issues\\src\\main\\resources\\EnglishData");
آدرس را نسبی بزنید
و نسبت به همین شاخه‌ی پروژه آدرس بدید که اگر سیستم تغییر کرد درست بمونه

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/Main.java
> +            assert filesList != null;
به جای این assert اگر خطا چاپ کنید مناسب‌تره

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/TakeInput.java
> +        Scanner scanner = new Scanner(System.in);
اسکنر از نظر اصولی باید بعد از اتمام کار close بشه

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/TakeInput.java
> +            String[] inputSplit = input.split("(\\s+)");
تقسیم ورودی به تعدادی کلمه وظیفه یک تابع دیگه است.

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/resources/EnglishData/57110
> +mother I have a 42 yr old male friend, misdiagnosed as havin osteopporosis for two years, who recently found out that hi illness is the rare Gaucher's disease.Gaucher's disease symptoms include: brit
فایل‌های تست و داده‌های آزمایشی ما نباید تو رپیو باشند.
کل پوشه را ایگنور کنید.

2021-07-26 09:42 UTC, MKasaei00 commented on Phase2/src/main/java/InvertedIndex.java
> +                String word = _word.toLowerCase();
نرمال‌سازی رشته‌ها جدا بشه که دست‌مون باز باشه در آینده کارهای بیش‌تری انجام بدیم

2021-07-26 13:28 UTC, MKasaei00 reviewed
<div dir='rtl'>

فقط فایل‌های تست متن را کامل از مخزن حذف کن.
خسته نباشی
</div>

2021-07-26 13:28 UTC, MKasaei00 commented on Phase2/.gitignore
> +/src/main/resources/EnglishData/
<div dir='rtl'>
علاوه بر اضافه شدن قانون ایگنور لازمه که فایل‌ها را هم دستی حذف کنید تا کاملا حذف بشه

</div>

2021-07-27 06:05 UTC, mjmaher987 commented
> فقط فایل‌های تست متن را کامل از مخزن حذف کن.
> خسته نباشی

ممنونم

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +                String word = _word.toLowerCase();
گذاشتن
underScore
اول اسم متغیر در نام‌گذاری جاوا کار درستی نیست از اسم‌های بهتری استفاده کنید مثلاً اولی
word
باشد و دومی
normalizedWord

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +            for (String _word : line.split("\\W+")) {
حلقه‌ی تو در تو مناسب نیست، حلقه‌ی داخلی به عنوان تابع استخراج شود

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +        int fileNumber = files.indexOf(file.getPath());
در این جا با هر بار کال کردن
indexOf
یک بار کل اعضای
files
پیمایش می‌شوند که
O(n)
است بهتر است از هش‌ست یا هش‌مپ استفاده شود

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +            for (String key : indexedWords.keySet()) {
فورها و ایف‌های تو در تو خوانایی کد را کاهش می‌دهند و در این جا چندین تابع می‌توان استخراج کرد و هم‌چنین از
guard clause
https://refactoring.guru/replace-nested-conditional-with-guard-clauses
استفاده کرد تا خوانایی کد افزایش پیدا کند

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +            returnArrayList.add(string.toLowerCase());
string.toLowerCase
این‌جا و جای دیگر تکرار شده است بهتر است به عنوان تابع استخراج شود چرا که اگر در آینده یکی از این دو مورد عوض شود و دیگری خیر کد دچار مشکل می‌شود

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +        } else if (answer.size() == 0 && commonWords != null) {
وقتی شرط قبلی در صورت ترو بودن ریترن می‌کند دیگر نیازی به نوشتن
else
نیست:
```java
if (answer.size() > 0 && commonWords != null) {
    answer.retainAll(commonWords);
    return answer;
}
if (answer.size() == 0 && commonWords != null) {
    return commonWords;
}
if (answer.size() == 0) {
    return null;
}
return answer;
```

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +        if (wordsToFindCommon.size() > 0) {
استفاده از
https://refactoring.guru/replace-nested-conditional-with-guard-clauses
توصیه میشه:
```java
if (wordsToFindCommon.size() <= 0){
    return null;
}
Set<String> commonWords = wordsToFindCommon.get(0);
if (wordsToFindCommon.size() == 1) {
    return commonWords;
}
for (int i = 1; i < wordsToFindCommon.size(); i++) {
    commonWords.retainAll(wordsToFindCommon.get(i));
}
return commonWords;
```
البته کلاً توصیه میشه به جای نال، یک ست خالی ریترن کنید

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/InvertedIndex.java
> +    private static class Tuple {
نام این کلاس اصلاً گویا نیست، نام مناسبی برای آن انتخاب کنید مثلاً
File
یا
FileInfo

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/Main.java
> +    public static void preprocesses() {
این تابع می‌تواند به یک کلاس سپرده شود که وظیفه‌ی
preprocess
کردن داده را دارد کلاس
main
صرفاً وظیفه‌ی سپردن کار به بقیه‌ی کلاس‌ها را دارد

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/Main.java
> +                    for (File file : filesList) {
داخل
else
می‌تونه یه تابع بشه

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/Main.java
> +                if (filesList == null) System.out.println("INVALID FILE LIST!");
این‌جا مناسب نیست که دارید
System.out.println
می‌زنید یا پایین تر که دارید
printStackTrace
می‌زنید رابط کاربری رو از منطق جدا کنید البته در فاز بعد که نوشتن تست هست به هر حال مجبور میشید این کار رو بکنید تا بتونید کدتون رو تست کنید

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/Main.java
> +                    new TakeInput(idx);
نیو کردن
TakeInput
ربطی به
preprocess
نداره و نباید تو این تابع باشه

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/TakeInput.java
> +public class TakeInput {
نام کلاس مناسب نیست، اسم کلاس نباید فعلی باشه می‌تونید مثلاً اسمش رو بذارید:
InputScanner

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/TakeInput.java
> +            showResult(processes(idx, plusStrings, minusStrings, normalStrings));
این‌جا هم نمایش داده با منطقش قاطی شده بهتره از هم جدا بشن و تو کلاس‌های مختلف این کار انجام بشه مثلاً یک کلاس که کارش نمایش داده به کاربر باشه و یک کلاس که کارش سرچ باشه بعد ابتدا سرچ انجام بشه بعد نتیجه به کلاس نمایش داده بشه

2021-07-27 06:57 UTC, mostmand commented on Phase2/src/main/java/TakeInput.java
> +    public TakeInput(InvertedIndex idx) {
اسم ورودی تابع رو کامل بذارید
index
نه
idx

2021-07-27 06:59 UTC, mostmand requested changes
بچه‌ها یه سری کامنت گذاشتم براتون

2021-07-27 07:07 UTC, mjmaher987 commented
> بچه‌ها یه سری کامنت گذاشتم براتون

ممنون

2021-07-27 08:51 UTC, mjmaher987 commented on Phase2/src/main/java/InvertedIndex.java
> +        int fileNumber = files.indexOf(file.getPath());
ببخشید متوجه منظورتون نشدیم.
یعنی دقیقا چه تغییری ایجاد کنیم؟

2021-07-31 07:50 UTC, arianpotter requested changes

2021-07-31 07:50 UTC, arianpotter commented on Phase2/src/main/java/InvertedIndex.java
> +    List<String> stopWords = Arrays.asList("a", "able", "about",
بهتر نیست به جای متغیر هاردکد شده از فایل استفاده کنید که تغییر و بروزرسانی لیست کلمات از بیرون برنامه راحت ترباشد
در ضمن اینجا میتوانستید متغیر را static final
تعریف کنید

2021-07-31 09:28 UTC, NaserFarajzade requested changes
بیشترین نکته ای که من بهش برخورد کردم توی کد هاتون استفاده از رشته داخل خود کد و تعریف نکردن متغیر های ثابت بود .

2021-07-31 09:28 UTC, NaserFarajzade commented on Phase2/src/main/java/PreProcessing.java
> +                if (filesList == null) return "INVALID FILE LIST!";
در این کلاس بهتر بود مسیر های فایل ها و همچنین مقدار بازگشتی تابع در خط 16
 ("INVALID FILE LIST!") 
به صورت متغیر final تعریف میشد

2021-07-31 09:28 UTC, NaserFarajzade commented on Phase2/src/main/java/InvertedIndex.java
> +        for (String key : indexedWords.keySet()) checkCommandMatcher(word, key, answer);
بنظرم اگه بدنه
if , for 
های تک خطی رو زیرشون بنویسیم خوانایی کد بیشتر میشه

2021-07-31 09:28 UTC, NaserFarajzade commented on Phase2/src/main/java/InputScannerView.java
> +            if (input.equals("--back")) break;
بهتره رشته "--back" رو به صورت متغیر کانستنت درنظر بگیرید

2021-08-01 02:24 UTC, MKasaei00 approved these changes

2021-08-03 06:10 UTC, parsasharify commented on Phase2/src/main/java/InvertedIndex.java
> +        for (String key : indexedWords.keySet()) checkCommandMatcher(word, key, answer);
این کار رو برای خوانایی بیشتر کد انجام دادیم داخل اینجا هندل میشه و داخل حلقه شلوغ نمیشه

2021-08-03 07:54 UTC, arianpotter approved these changes

2021-08-07 05:42 UTC, mostmand approved these changes

2021-08-07 06:13 UTC, NaserFarajzade approved these changes
همه چی اوکی بود بنظرم

2021-08-07 07:35 UTC, merged