PR of Phase4
Star-Academy/Summer1400-SE-Team14 pull request #4
Opened 2021-08-03 12:03 UTC by mjmaher987

2021-08-07 04:54 UTC, MKasaei00 requested changes

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/Process.cs
> +            foreach (Student student in orderedStudentsByAverage)
می‌تونید از 
var 
استفاده کنید

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/Process.cs
> +        private void PrintBestThreeStudents(IEnumerable orderedStudentsByAverage)
برای 
IEnumerable
نوع مشخص کنید

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/Program.cs
> +            var unused = new ReadFiles();
به نظر بهتره که توی کانستراکتور مستقیم خیلی کارها را انجام ندید و نیاز باشه که یک تابع مجزا فراخوانی بشه تا اجرای برنامه شروع بشه

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/ReadFiles.cs
> +            const string fileName = "C:\\Users\\mjmah\\OneDrive\\Desktop\\new\\Phase-4\\lessons.json";
آدرس نسبی بدید بهتره

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/ReadFiles.cs
> +            const string fileName = "C:\\Users\\mjmah\\OneDrive\\Desktop\\new\\Phase-4\\Students.json";
آدرس نسبی بدید بهتره

2021-08-07 04:54 UTC, MKasaei00 commented on Phase-4/Students.json
> +﻿[
حضور این‌فایل‌ها توی ریپو لازم نیست ولی چون حجم فایل‌ها کمه و ساختار داده را مشخص می‌کنه به نظرم مشکلی هم نداره

2021-08-07 04:54 UTC, MKasaei00 commented on .idea/.idea.Phase-4/.idea/.gitignore
> +/httpRequests/
فایل‌های 
dll
هم باید توی ایگنور باشند و از ریپو حذف بشن 

فایل ایگنور کامل نیست

2021-08-07 11:36 UTC, mostmand requested changes

2021-08-07 11:36 UTC, mostmand commented on Phase-4/Process.cs
> +            foreach (Student student in orderedStudentsByAverage)
می‌تونید از
LINQ
استفاده کنید به این صورت:
```csharp
var topThreeStudents = orderedStudentsByAverage.Take(3);
```

2021-08-07 11:36 UTC, mostmand commented on Phase-4/Process.cs
> +    public class Process
اسم کلاس بهتره فعلی باشه مثلاً
StudentProcessor

2021-08-07 11:36 UTC, mostmand commented on Phase-4/Process.cs
> +            Student.AllStudents = students;
این تابع بهتره مثلاً تو یه کلاسی باشه به اسم
Database
که اون وظیفه‌ی نگه‌داری دانشجوها و نمراتشون رو داره و بهتره
AllStudents
توی کلاس
Student
نباشه

2021-08-07 11:36 UTC, mostmand commented on Phase-4/Process.cs
> +            Student.AllStudents = students;
هم‌چنین تابع 
SetLessonsForStudents

2021-08-07 11:36 UTC, mostmand commented on Phase-4/Process.cs
> +            foreach (Student student in orderedStudentsByAverage)
بهتره پیدا کردن سه دانشجوی برتر جدای از پرینت کردن اون‌ها باشه و حداقلش اینه که توی دو تا تابع مختلف باشه

2021-08-07 11:36 UTC, mostmand commented on Phase-4/ReadFiles.cs
> +            const string fileName = "C:\\Users\\mjmah\\OneDrive\\Desktop\\new\\Phase-4\\Students.json";
بهتر که چه عرض کنم باید آدرس نسبی بدید چون این‌جوری الان من کدتون رو کلون کنم رو سیستم من خطا می‌خوره

2021-08-07 11:36 UTC, mostmand commented on Phase-4/ReadFiles.cs
> +            var students = JsonSerializer.Deserialize<List<Student>>(jsonString);
بچه‌ها
Dependency Inversion Principle
رو رعایت کنید و برای دیسریالایز کردن از یه اینترفیس بهره بگیرید

2021-08-08 19:03 UTC, arianpotter requested changes
برای کلاس ها اینترفیس بسازید و از آنها استفاده کنید بهتر است
ازبه نظرم gitignore بهتری استفاده کنید که فایل های اضافه وارد ریپو نشوند

2021-08-09 10:17 UTC, NaserFarajzade requested changes

2021-08-09 10:17 UTC, NaserFarajzade commented on Phase-4/Student.cs
> +        private List<LessonClass> allLessons = new List<LessonClass>();
فکر میکنم این جاها بهتر باشه از var استفاده بشه

2021-08-10 12:29 UTC, mjmaher987 commented on .idea/.idea.Phase-4/.idea/.gitignore
> +/httpRequests/
ممنون.
فقط ببخشید فایلهای dll
کجا هستند ؟

2021-08-10 12:59 UTC, parsasharify commented on Phase-4/Student.cs
> +        private List<LessonClass> allLessons = new List<LessonClass>();
برای چی؟ متغیر ها داخل کلاس هستند

2021-08-10 13:00 UTC, parsasharify commented on Phase-4/ReadFiles.cs
> +            var students = JsonSerializer.Deserialize<List<Student>>(jsonString);
منظورتون اینه که این توابع داخل یک اینترفیس باشند؟

2021-08-11 04:49 UTC, MKasaei00 approved these changes

2021-08-12 10:54 UTC, arianpotter approved these changes

2021-08-16 03:50 UTC, mostmand approved these changes
دو تا کامنت ریز گذاشتم درست کنید و مرج کنید

2021-08-16 03:50 UTC, mostmand commented on Phase-4/Program.cs
> +    public class P
اسم کلاس خیلی گویاست😂
خود
Program
چه مشکلی داره که گذاشتید
P?

2021-08-16 03:50 UTC, mostmand commented on Phase-4/DataBase.cs
> +        public static List<Student> AllStudents { set; get; }
بهتره این پراپرتی استاتیک نباشه و به جاش کلاس
Database
سینگلتون باشه

2021-08-17 07:02 UTC, merged