PR of Phase3
Star-Academy/Summer1400-SE-Team14 pull request #6
Opened 2021-08-07 07:37 UTC by mjmaher987

2021-08-07 11:23 UTC, mostmand requested changes
بچه‌ها یه سری کامنت گذاشتم که ایرادات اساسی هستن

2021-08-07 11:23 UTC, mostmand commented on src/main/java/InputScannerView.java
> +        if (!string.equals("")) {
از
string.isEmpty
استفاده کنید

2021-08-07 11:23 UTC, mostmand commented on src/main/java/InputScanner.java
> +    public Set<String> getOrder(String input) {
عمل جداکردن کلماتی که + یا - دارند را به کلاس دیگری بسپارید و عملیات جستجو در اینورتد ایندکس را از آن جدا کنید

2021-08-07 11:23 UTC, mostmand commented on src/main/java/InvertedIndex.java
> +    private String convertToLowerCase(String wordsInFiles) {
بهتره اسم این تابع
normalize
باشه

2021-08-07 11:23 UTC, mostmand commented on src/main/java/PreProcessing.java
> +                new InputScannerView(index, startString);
صرفاً کلاس رو نیو می‌کنید و هیچ استفاده‌ای نمی‌کنید؟

2021-08-07 11:23 UTC, mostmand commented on src/main/java/Main.java
> +        new ViewPreProcessing();
صرفاً کلاس رو نیو می‌کنید و هیچ استفاده‌ای نمی‌کنید؟

2021-08-07 11:23 UTC, mostmand commented on src/main/java/Main.java
> +        new ViewPreProcessing();
بهتره کارها رو به توابع اون کلاس بسپارید و کانستراکتور صرفاً وظیفه‌ی ساخت اون کلاس رو بر عهده داشته باشه

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +public class JavaTest {
اسم کلاس رو مطابق کلاسی بذارید که می‌خواید براش یونیت تست بنویسید مثلا می‌خواید کلاس
Preprocessor
رو تست کنید اسم کلاس رو بذارید
PreprocessorTests

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +        filesTest.add(file.getPath());
این نحوه‌ی درست تست نوشتن نیست شما نتیجه‌ی مورد انتظارتون باید یه مقدار مشخص باشه نه که برید از فایل بخونیدش

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +        pathRoots.add(file.getPath());
این کار هم مثل کامنتی که برای تابع 
test
نوشتم کار درستی نیست

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +    public void test() throws IOException {
اسم تابع‌های تست رو گویا انتخاب کنید

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +        pathRoots.add(file.getPath());
برای تابع‌های بعدی‌تون هم همین ایراد وارده

2021-08-07 11:23 UTC, mostmand commented on src/test/java/JavaTest.java
> +public class JavaTest {
به ازای هر کلاس که مورد تست قرار می‌دید یه کلاس تست جداگانه بنویسید

2021-08-08 18:53 UTC, arianpotter requested changes
فایل های باینری را معمولا در ریپو بارگذاری نمیکنند

2021-08-09 04:24 UTC, MKasaei00 requested changes

2021-08-09 04:24 UTC, MKasaei00 commented on .idea/.gitignore
> +# Default ignored files
ایگنور فایل‌های 
intellij idea
را هم اضافه کنین و فایل‌های ترک دنبال شده را از ریپو حذف کنین

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InputScanner.java
> +        Matcher matcher1 = pattern1.matcher(string);
اسم متغییرها را معنی دار بذارید

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InputScannerView.java
> +                if (string.equals("--back")) break;
رشته‌ی لازم برای خارج شدن از برنامه را اگر به صورت ثابت در کلاس تعریف کنید بهتره

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InputScannerView.java
> +        for (String s : answer) System.out.println(s);
به نظرم در هر صورت برای حلقه ها و شرط‌ها از کروشه استفاده کنید مستقل از تعداد خط دستورات

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InvertedIndex.java
> +    Map<String, List<FileInfo>> indexedWords = new HashMap<>();
فکر می‌کنم بتونید این فیلد را فاینال تعریف کنید

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InvertedIndex.java
> +        for (String wordsInFiles : line.split("\\W+")) {
به نظرم تکه تکه کردن رشته به تعدادی کلمه و نرمال کلمات دو وظیفه مستقل هستند

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InvertedIndex.java
> +        for (String word : wordsToFind) findWordInFiles(word, answer);
کروشه

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/InvertedIndex.java
> +        for (String word : wordsToFind) findWordInFiles(word, answer);
و بعضا جاهای دیگه

2021-08-09 04:24 UTC, MKasaei00 commented on src/main/java/ViewPreProcessing.java
> +           String result = PreProcessing.preprocesses("/EnglishData" ,"1");
بهتره آدرس خوندن و پیش‌پردازش از ورودی گرفته بشه

2021-08-09 04:24 UTC, MKasaei00 commented on src/test/java/JavaTest.java
> +//    }
کامنت‌های اضافی را پاک کنین

2021-08-09 04:24 UTC, MKasaei00 commented on src/test/java/JavaTest.java
> +        Assertions.assertEquals(answer, invertedIndex.findCommonFiles(answer , new  ArrayList<Set<String>>()));
معمولا بهتره که تست‌ها فقط و فقط یک 
assert
داشته باشند
و فقط یک هدف واحد را بررسی کنند.

2021-08-09 04:24 UTC, MKasaei00 commented on .idea/.gitignore
> +/dataSources/
فایل‌های باینری را هم از ریپو حذف کنید

2021-08-09 10:07 UTC, NaserFarajzade requested changes
گفتنی ها رو بچه ها گفتن من چیز جدیدی به ذهنم نرسید دیگه

2021-08-10 06:11 UTC, mjmaher987 commented on src/main/java/PreProcessing.java
> +                new InputScannerView(index, startString);
از طریق کانستراکتور یک تابع را صدا میزنه

2021-08-10 06:23 UTC, mjmaher987 commented on src/test/java/JavaTest.java
> +        filesTest.add(file.getPath());
جواب مورد انتظار را از فایل نمیخوانیم.
آن بخش قسمتی از تست در حال ساخت است.
جواب مورد انتظار این تست یک لیست حاوی آدرسی است که آن آدرس را به آن داده ایم.

2021-08-10 07:05 UTC, mjmaher987 commented on src/main/java/InputScanner.java
> +    public Set<String> getOrder(String input) {
یعنی کدام تابع را در کلاس دیگر بنویسیم؟

2021-08-11 04:52 UTC, MKasaei00 approved these changes

2021-08-12 10:53 UTC, arianpotter approved these changes

2021-08-16 03:47 UTC, mostmand requested changes
البته بچه‌ها به نظرم دیگر روی جاوا وقت نگذارید و این پول ریکوئست رو مرج کنید

2021-08-16 03:47 UTC, mostmand commented on src/main/java/InputScanner.java
> +    public Set<String> getOrder(String input) {
در کلاس دیگر تابعی داشته باشید که عبارت سرچ‌شده‌ی کاربر را بگیرد و سه تا لیست از کلمات بدهد که این سه لیست به ترتیب کلمات بی علامت، کلمات + دار و کلمات - دار باشند. یعنی پارس کردن کوئری کاربر را به کلاس دیگری بسپارید.

2021-08-16 03:47 UTC, mostmand commented on src/test/java/JavaTest.java
> +//    @Test
کد کامنت شده پاک شود

2021-08-16 03:47 UTC, mostmand commented on src/test/java/JavaTest.java
> +public class JavaTest {
همه‌ی تست‌ها را در یک کلاس ننویسید و به ازای هر کلاس که می‌خواهید تست کنید یک کلاس تست داشته باشید.

2021-08-21 06:45 UTC, merged